import { useEffect, useState } from 'react'
import { collection, getDocs, orderBy, query } from 'firebase/firestore'
import { db } from '../firebase'
import FeaturedCard from '../components/FeaturedCard'

export default function Featured() {
  const [state, setState] = useState({ loading: true, articles: [], error: false })
  useEffect(() => { let active = true; getDocs(query(collection(db, 'featured_articles'), orderBy('created_at', 'desc'))).then((snapshot) => active && setState({ loading: false, articles: snapshot.docs.map((doc) => ({ id: doc.id, ...doc.data() })), error: false })).catch(() => active && setState({ loading: false, articles: [], error: true })); return () => { active = false } }, [])
  return <main className="mx-auto max-w-7xl px-5 py-10 sm:px-7 sm:py-14"><div className="max-w-3xl border-b border-ink/15 pb-8 dark:border-white/15"><p className="text-xs font-bold uppercase tracking-[.2em] text-coral">Briefly presents</p><h1 className="mt-3 font-display text-5xl leading-none text-ink dark:text-paper sm:text-7xl">Featured stories</h1><p className="mt-5 max-w-2xl text-base leading-7 text-ink/65">In-depth stories synthesized across multiple outlets, with original reporting cited throughout.</p></div>{state.loading && <div className="mt-8 grid gap-6 sm:grid-cols-2">{[1,2,3,4].map((item) => <div key={item} className="h-80 animate-pulse bg-moss/10"/>)}</div>}{!state.loading && state.error && <div className="mt-8 border border-coral/25 bg-coral/5 p-8"><h2 className="font-display text-2xl text-ink dark:text-paper">Couldn’t load featured stories</h2><p className="mt-2 text-sm text-ink/65">Please check your connection and refresh to try again.</p></div>}{!state.loading && !state.error && state.articles.length === 0 && <div className="mt-8 border border-dashed border-ink/20 p-10 text-center"><p className="font-display text-3xl text-ink dark:text-paper">No featured stories yet.</p><p className="mt-3 text-sm leading-6 text-ink/60">These appear when a story is trending across multiple sources. Check back soon.</p></div>}{!state.loading && !state.error && state.articles.length > 0 && <div className="mt-8 grid gap-7 sm:grid-cols-2">{state.articles.map((article) => <FeaturedCard key={article.id} article={article}/>)}</div>}</main>
}
